export const enum Models {
	ServerStat = 'server-stats',
	RawJob = 'rawjobs',
	RawCompany = 'rawcompanies',
	Job = 'jobs',
	Company = 'companies',
	RawNews = 'rawnews',
	NewsCategory = 'newscategories',
	News = 'news',
	Designation = 'designations',
	Industry = 'industries',
	JobFunction = 'jobfunctions',
	Commitment = 'commitments',
	Skill = 'skills',
	City = 'cities',
	State = 'states',
	Country = 'countries',
	User = 'users',
	AppliedJob = 'appliedjobs',
	JobMatchReason = 'jobmatchreasons',
	NotInterestedJob = 'notinterestedjobs',
	ReportJob = 'reportjobs',
	ReportType = 'reporttypes',
	SavedJob = 'savedjobs',
  	LinkedInProfile = "linkedinprofiles",
	OpenAiBatch = 'openaibatches',
}
